"""initial schema

Revision ID: e18f13e89949
Revises: 
Create Date: 2026-08-24 11:06:50.993972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18f13e89949'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=False),
    sa.Column('pseudonymous_tag', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_ref')
    )
    op.create_index(op.f('ix_subjects_pseudonymous_tag'), 'subjects', ['pseudonymous_tag'], unique=False)
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.create_table('api_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_credentials_subject_id'), 'api_credentials', ['subject_id'], unique=False)
    op.create_index(op.f('ix_api_credentials_tenant_id'), 'api_credentials', ['tenant_id'], unique=False)
    op.create_table('generation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('original_output_hash', sa.String(length=64), nullable=False),
    sa.Column('watermarked_output_hash', sa.String(length=64), nullable=False),
    sa.Column('opportunity_count', sa.Integer(), nullable=False),
    sa.Column('embedded_count', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_events_subject_id'), 'generation_events', ['subject_id'], unique=False)
    op.create_index(op.f('ix_generation_events_tenant_id'), 'generation_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_events_tenant_id'), table_name='generation_events')
    op.drop_index(op.f('ix_generation_events_subject_id'), table_name='generation_events')
    op.drop_table('generation_events')
    op.drop_index(op.f('ix_api_credentials_tenant_id'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_subject_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_pseudonymous_tag'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('tenants')
    # ### end Alembic commands ###
